export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCHING_INGREDIENTS_FAILED = 'FETCHING_INGREDIENTS_FAILED';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_UNEXPECTED_ERROR = 'AUTH_UNEXPECTED_ERROR';
export const LOGIN_EXPIRES = 'LOGIN_EXPIRES';
export const LOGOUT = 'LOGOUT';

export const REQUEST_FETCHING_ORDERS = 'REQUEST_FETCHING_ORDERS';
export const FETCHING_ORDERS_SUCCESS = 'FETCHING_ORDERS_SUCCESS';
export const FETCHING_ORDERS_FAILED = 'FETCHING_ORDERS_FAILED';
export const REMOVE_ORDERS_IN_LOGOUT = 'REMOVE_ORDERS_IN_LOGOUT'
export const FETCHING_ORDERS_NETWORK_ERROR = 'FETCHING_ORDERS_NETWORK_ERROR';
